version: "3"

services:
  database:
    image: postgres
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: "directus"
      POSTGRES_DB: "directus"

  directus:
    image: directus/directus:11.0.2
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      SECRET: "replace-with-secure-random-value"

      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"

      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      WEBSOCKETS_ENABLED: "true"

      CORS_ENABLED: true
      CORS_ORIGIN: http://localhost:3000
      CORS_METHODS: GET,POST,PUT,DELETE,PATCH
      CORS_ALLOWED_HEADERS: Content-Type,Authorization,Access-Control-Allow-Headers
